package vcclient

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"
)

type Jobs []struct {
	TriggerDependencies []interface{} `json:"TriggerDependencies"`
	Triggers            []struct {
		ExpireActionType int         `json:"ExpireActionType"`
		ExpireType       int         `json:"ExpireType"`
		Result           interface{} `json:"Result"`
		TEvent           interface{} `json:"TEvent"`
		TTime            struct {
			TimeTriggerType    int       `json:"TimeTriggerType"`
			IntervalType       int       `json:"IntervalType"`
			SpecificType       int       `json:"SpecificType"`
			FirstLastType      int       `json:"FirstLastType"`
			IntervalValue      int       `json:"IntervalValue"`
			FirstLastWeekDay   int       `json:"FirstLastWeekDay"`
			InitDate           time.Time `json:"InitDate"`
			IntervalDays       []bool    `json:"IntervalDays"`
			IntervalWeekDays   []bool    `json:"IntervalWeekDays"`
			AllYears           bool      `json:"AllYears"`
			YearIsBetween      bool      `json:"YearIsBetween"`
			AllMonths          bool      `json:"AllMonths"`
			YearBetweenStart   int       `json:"YearBetweenStart"`
			YearBetweenStop    int       `json:"YearBetweenStop"`
			Years              []int     `json:"Years"`
			MonthsIsBetween    bool      `json:"MonthsIsBetween"`
			MonthBetweenStart  int       `json:"MonthBetweenStart"`
			MonthBetweenStop   int       `json:"MonthBetweenStop"`
			Months             []bool    `json:"Months"`
			AllDays            bool      `json:"AllDays"`
			DayType            bool      `json:"DayType"`
			DaysIsBetween      bool      `json:"DaysIsBetween"`
			DayBetweenStart    int       `json:"DayBetweenStart"`
			DayBetweenStop     int       `json:"DayBetweenStop"`
			Days               []bool    `json:"Days"`
			AllHours           bool      `json:"AllHours"`
			HoursIsBetween     bool      `json:"HoursIsBetween"`
			HourBetweenStart   int       `json:"HourBetweenStart"`
			HourBetweenStop    int       `json:"HourBetweenStop"`
			Hours              []bool    `json:"Hours"`
			AllMinutes         bool      `json:"AllMinutes"`
			MinutesIsBetween   bool      `json:"MinutesIsBetween"`
			MinuteBetweenStart int       `json:"MinuteBetweenStart"`
			MinuteBetweenStop  int       `json:"MinuteBetweenStop"`
			Minutes            []bool    `json:"Minutes"`
			AllSeconds         bool      `json:"AllSeconds"`
			Seconds            []bool    `json:"Seconds"`
			SecondsIsBetween   bool      `json:"SecondsIsBetween"`
			SecondBetweenStart int       `json:"SecondBetweenStart"`
			SecondBetweenStop  int       `json:"SecondBetweenStop"`
			DateNextExecution  time.Time `json:"DateNextExecution"`
		} `json:"TTime"`
		AutoDescription        bool      `json:"AutoDescription"`
		AutoRefreshDescription bool      `json:"AutoRefreshDescription"`
		CurrentCPUTime         float64   `json:"CurrentCPUTime"`
		CPUTime                string    `json:"CPUTime"`
		ID                     string    `json:"Id"`
		TriggerCount           int       `json:"TriggerCount"`
		JobID                  string    `json:"JobId"`
		Description            string    `json:"Description"`
		Active                 bool      `json:"Active"`
		FirstRun               time.Time `json:"FirstRun"`
		ExpirationEnabled      bool      `json:"ExpirationEnabled"`
		ExpirationDate         time.Time `json:"ExpirationDate"`
		TimesUntilExpire       int       `json:"TimesUntilExpire"`
		UseTimeOut             bool      `json:"UseTimeOut"`
		TimeOutHours           int       `json:"TimeOutHours"`
		TimeOutMinutes         int       `json:"TimeOutMinutes"`
		TimeOutSeconds         int       `json:"TimeOutSeconds"`
		TimeOutTime            string    `json:"TimeOutTime"`
		IgnoreServerOff        bool      `json:"IgnoreServerOff"`
		IsUTCOffsetSet         bool      `json:"IsUTCOffsetSet"`
		UTCOffsetTicks         int64     `json:"UTCOffsetTicks"`
		UTCOffset              string    `json:"UTCOffset"`
		TriggerType            int       `json:"TriggerType"`
		TriggerDebugging       bool      `json:"TriggerDebugging"`
	} `json:"Triggers"`
	ResetTriggerDepedency bool          `json:"ResetTriggerDepedency"`
	Variables             []interface{} `json:"Variables"`
	GroupOverride         []interface{} `json:"GroupOverride"`
	Flow                  []interface{} `json:"Flow"`
	JobLoops              []interface{} `json:"JobLoops"`
	Tasks                 []struct {
		StartNotifications    []interface{} `json:"StartNotifications"`
		CompleteNotifications []interface{} `json:"CompleteNotifications"`
		ErrorNotifications    []interface{} `json:"ErrorNotifications"`
		Conditions            []interface{} `json:"Conditions"`
		TimeOut               struct {
			Use           bool `json:"Use"`
			Hours         int  `json:"Hours"`
			Minutes       int  `json:"Minutes"`
			Seconds       int  `json:"Seconds"`
			ConsiderError bool `json:"ConsiderError"`
		} `json:"TimeOut"`
		Stats struct {
			Status              int       `json:"Status"`
			JobID               string    `json:"JobId"`
			TaskID              string    `json:"TaskId"`
			Active              bool      `json:"Active"`
			StandardOutput      string    `json:"StandardOutput"`
			StandardError       string    `json:"StandardError"`
			ExitCode            int       `json:"ExitCode"`
			ExitCodeResult      int       `json:"ExitCodeResult"`
			ExecutionTime       float64   `json:"ExecutionTime"`
			NoExecutes          int       `json:"NoExecutes"`
			Result              string    `json:"Result"`
			DateLastExited      time.Time `json:"DateLastExited"`
			DateLastExecution   time.Time `json:"DateLastExecution"`
			DateCreated         string    `json:"DateCreated"`
			DateModified        time.Time `json:"DateModified"`
			CPUTime             float64   `json:"CPUTime"`
			ProcessCPUTime      float64   `json:"ProcessCPUTime"`
			NotificationCPUTime float64   `json:"NotificationCPUTime"`
		} `json:"Stats"`
		OnError struct {
			CausesError          int           `json:"CausesError"`
			ErrorList            []interface{} `json:"ErrorList"`
			ErrorAction          int           `json:"ErrorAction"`
			TaskID               interface{}   `json:"TaskId"`
			JobID                interface{}   `json:"JobId"`
			RetryTimes           int           `json:"RetryTimes"`
			RunFollowingTasks    bool          `json:"RunFollowingTasks"`
			Minutes              int           `json:"Minutes"`
			Seconds              int           `json:"Seconds"`
			ExitCodeCollectionID string        `json:"ExitCodeCollectionId"`
			RaiseErrorAction     int           `json:"RaiseErrorAction"`
			ExitCode             int           `json:"ExitCode"`
			EventCondition       int           `json:"EventCondition"`
			ValueType            int           `json:"ValueType"`
			ConditionType        int           `json:"ConditionType"`
			ConditionValue1      string        `json:"ConditionValue1"`
			ConditionValue2      string        `json:"ConditionValue2"`
		} `json:"OnError"`
		Result           interface{}   `json:"Result"`
		TaskDebugging    bool          `json:"TaskDebugging"`
		ConditionsArray  []interface{} `json:"ConditionsArray"`
		ID               string        `json:"Id"`
		JobID            string        `json:"JobId"`
		Order            int           `json:"Order"`
		Name             string        `json:"Name"`
		Description      interface{}   `json:"Description"`
		StoreSTDOut      bool          `json:"StoreSTDOut"`
		StoreSTDErr      bool          `json:"StoreSTDErr"`
		ExecutionContext struct {
			IsLocalConnection              bool   `json:"IsLocalConnection"`
			ConnectionID                   string `json:"ConnectionId"`
			InheritExitCode                bool   `json:"InheritExitCode"`
			ExecutionType                  int    `json:"ExecutionType"`
			ForegroundExecuteType          int    `json:"ForegroundExecuteType"`
			UserName                       string `json:"UserName"`
			SessionID                      int    `json:"SessionID"`
			AnySessionID                   bool   `json:"AnySessionID"`
			BeforeExecutionLogon           bool   `json:"BeforeExecutionLogon"`
			BeforeExecutionLogonCredential string `json:"BeforeExecutionLogonCredential"`
			OtherSessionAction             int    `json:"OtherSessionAction"`
			AfterUnlockLock                bool   `json:"AfterUnlockLock"`
			AfterExecutionAction           int    `json:"AfterExecutionAction"`
		} `json:"ExecutionContext"`
		CodePage int `json:"CodePage"`
		TaskType int `json:"TaskType"`
		Flow     []struct {
			ID              string `json:"Id"`
			FlowOrigin      int    `json:"FlowOrigin"`
			ActionType      int    `json:"ActionType"`
			RetryFailAction int    `json:"RetryFailAction"`
			TimeOut         struct {
				Hours   string `json:"Hours"`
				Minutes string `json:"Minutes"`
				Seconds string `json:"Seconds"`
			} `json:"TimeOut"`
			EventType          int    `json:"EventType"`
			EventCondition     int    `json:"EventCondition"`
			ValueType          int    `json:"ValueType"`
			ConditionType      int    `json:"ConditionType"`
			ConditionValue1    string `json:"ConditionValue1"`
			ConditionValue2    string `json:"ConditionValue2"`
			Minutes            int    `json:"Minutes"`
			Seconds            int    `json:"Seconds"`
			NotificationID     string `json:"NotificationId"`
			TaskID             string `json:"TaskId"`
			JobID              string `json:"JobId"`
			RunJobAsynchronous bool   `json:"RunJobAsynchronous"`
			DeactivateJob      bool   `json:"DeactivateJob"`
			RetryTimes         int    `json:"RetryTimes"`
			RunFollowingTasks  bool   `json:"RunFollowingTasks"`
			DeactivateTask     bool   `json:"DeactivateTask"`
		} `json:"Flow"`
		Execute           interface{} `json:"Execute"`
		ExecuteScript     interface{} `json:"ExecuteScript"`
		DotNetExecute     interface{} `json:"DotNetExecute"`
		RemoteExecute     interface{} `json:"RemoteExecute"`
		Kill              interface{} `json:"Kill"`
		RemoteKill        interface{} `json:"RemoteKill"`
		AS400Command      interface{} `json:"AS400Command"`
		SendKeys          interface{} `json:"SendKeys"`
		SQL               interface{} `json:"SQL"`
		Ssis              interface{} `json:"SSIS"`
		Dts               interface{} `json:"DTS"`
		Ssisdb            interface{} `json:"SSISDB"`
		Ssrs              interface{} `json:"SSRS"`
		TableCopy         interface{} `json:"TableCopy"`
		CopyFile          interface{} `json:"CopyFile"`
		Archive           interface{} `json:"Archive"`
		ArchiveCompress   interface{} `json:"ArchiveCompress"`
		ArchiveDecompress interface{} `json:"ArchiveDecompress"`
		SyncFile          interface{} `json:"SyncFile"`
		Ftp               interface{} `json:"FTP"`
		Pgp               interface{} `json:"PGP"`
		PGPEncrypt        interface{} `json:"PGPEncrypt"`
		PGPDecrypt        interface{} `json:"PGPDecrypt"`
		Wait              interface{} `json:"Wait"`
		FileDelete        interface{} `json:"FileDelete"`
		FileRename        interface{} `json:"FileRename"`
		FileRead          interface{} `json:"FileRead"`
		FileWrite         interface{} `json:"FileWrite"`
		FileTouch         interface{} `json:"FileTouch"`
		FilesList         interface{} `json:"FilesList"`
		FolderDelete      interface{} `json:"FolderDelete"`
		FolderCreate      interface{} `json:"FolderCreate"`
		FolderRename      interface{} `json:"FolderRename"`
		JobTaskControl    interface{} `json:"JobTaskControl"`
		ExportSettings    struct {
			Settings          []interface{} `json:"Settings"`
			Credential        string        `json:"Credential"`
			UseDefaultPath    bool          `json:"UseDefaultPath"`
			Path              interface{}   `json:"Path"`
			ExportAllSettings bool          `json:"ExportAllSettings"`
			Password          interface{}   `json:"Password"`
		} `json:"ExportSettings"`
		Email                         interface{}   `json:"Email"`
		SSH                           interface{}   `json:"SSH"`
		SystemLogoff                  interface{}   `json:"SystemLogoff"`
		SystemShutdown                interface{}   `json:"SystemShutdown"`
		SystemRestart                 interface{}   `json:"SystemRestart"`
		SystemLock                    interface{}   `json:"SystemLock"`
		SystemUnLock                  interface{}   `json:"SystemUnLock"`
		SystemHibernate               interface{}   `json:"SystemHibernate"`
		SystemStandby                 interface{}   `json:"SystemStandby"`
		SystemWakeUp                  interface{}   `json:"SystemWakeUp"`
		SystemWakeUpOnLan             interface{}   `json:"SystemWakeUpOnLan"`
		SystemControlMonitor          interface{}   `json:"SystemControlMonitor"`
		ServiceStart                  interface{}   `json:"ServiceStart"`
		ServiceRestart                interface{}   `json:"ServiceRestart"`
		ServiceStop                   interface{}   `json:"ServiceStop"`
		VariableSet                   interface{}   `json:"VariableSet"`
		VariableRemove                interface{}   `json:"VariableRemove"`
		VariableCalculate             interface{}   `json:"VariableCalculate"`
		PrintDocument                 interface{}   `json:"PrintDocument"`
		NetPing                       interface{}   `json:"NetPing"`
		DesktopMacro                  interface{}   `json:"DesktopMacro"`
		Robot                         interface{}   `json:"Robot"`
		PlaySound                     interface{}   `json:"PlaySound"`
		Registry                      interface{}   `json:"Registry"`
		OfficeMacro                   interface{}   `json:"OfficeMacro"`
		XMLCreateNode                 interface{}   `json:"XMLCreateNode"`
		XMLReadNode                   interface{}   `json:"XMLReadNode"`
		XMLEditNode                   interface{}   `json:"XMLEditNode"`
		XMLDeleteNode                 interface{}   `json:"XMLDeleteNode"`
		XMLTransform                  interface{}   `json:"XMLTransform"`
		XMLValidate                   interface{}   `json:"XMLValidate"`
		XMLSign                       interface{}   `json:"XMLSign"`
		XMLVerify                     interface{}   `json:"XMLVerify"`
		InstantMessaging              interface{}   `json:"InstantMessaging"`
		ADCreateGroup                 interface{}   `json:"ADCreateGroup"`
		ADCreateObject                interface{}   `json:"ADCreateObject"`
		ADCreateUser                  interface{}   `json:"ADCreateUser"`
		ADDeleteObject                interface{}   `json:"ADDeleteObject"`
		ADGetGroupMembers             interface{}   `json:"ADGetGroupMembers"`
		ADGetObjectPath               interface{}   `json:"ADGetObjectPath"`
		ADGetObjectProperty           interface{}   `json:"ADGetObjectProperty"`
		ADListObjectPaths             interface{}   `json:"ADListObjectPaths"`
		ADModifyGroup                 interface{}   `json:"ADModifyGroup"`
		ADModifyUser                  interface{}   `json:"ADModifyUser"`
		ADMoveObject                  interface{}   `json:"ADMoveObject"`
		ADRenameObject                interface{}   `json:"ADRenameObject"`
		ADSetObjectProperty           interface{}   `json:"ADSetObjectProperty"`
		HTTP                          interface{}   `json:"HTTP"`
		Telnet                        interface{}   `json:"Telnet"`
		Rsh                           interface{}   `json:"RSH"`
		RLogin                        interface{}   `json:"RLogin"`
		RExec                         interface{}   `json:"RExec"`
		CheckPort                     interface{}   `json:"CheckPort"`
		SerialSend                    interface{}   `json:"SerialSend"`
		WebMacro                      interface{}   `json:"WebMacro"`
		ExchangeCreateObject          interface{}   `json:"ExchangeCreateObject"`
		ExchangeDeleteObject          interface{}   `json:"ExchangeDeleteObject"`
		ExchangeDeleteObjects         interface{}   `json:"ExchangeDeleteObjects"`
		ExchangeModifyObject          interface{}   `json:"ExchangeModifyObject"`
		ExchangeGetObjects            interface{}   `json:"ExchangeGetObjects"`
		AssemblyExecute               interface{}   `json:"AssemblyExecute"`
		WebService                    interface{}   `json:"WebService"`
		SNMPGet                       interface{}   `json:"SNMPGet"`
		SNMPGetNext                   interface{}   `json:"SNMPGetNext"`
		SNMPGetBulk                   interface{}   `json:"SNMPGetBulk"`
		SNMPSet                       interface{}   `json:"SNMPSet"`
		SNMPWalk                      interface{}   `json:"SNMPWalk"`
		WebDAVListItems               interface{}   `json:"WebDAVListItems"`
		WebDAVListFolders             interface{}   `json:"WebDAVListFolders"`
		WebDAVCreateFolder            interface{}   `json:"WebDAVCreateFolder"`
		WebDAVDownload                interface{}   `json:"WebDAVDownload"`
		WebDAVUpload                  interface{}   `json:"WebDAVUpload"`
		WebDAVDelete                  interface{}   `json:"WebDAVDelete"`
		WebDAVCopyFiles               interface{}   `json:"WebDAVCopyFiles"`
		EventLogRead                  interface{}   `json:"EventLogRead"`
		EventLogWrite                 interface{}   `json:"EventLogWrite"`
		ExcelGetCell                  interface{}   `json:"ExcelGetCell"`
		ExcelSetCell                  interface{}   `json:"ExcelSetCell"`
		ExcelConvert                  interface{}   `json:"ExcelConvert"`
		ExcelRecalculate              interface{}   `json:"ExcelRecalculate"`
		ExcelGetRowCount              interface{}   `json:"ExcelGetRowCount"`
		ExcelCreate                   interface{}   `json:"ExcelCreate"`
		FileConcatenate               interface{}   `json:"FileConcatenate"`
		PowerShell                    interface{}   `json:"PowerShell"`
		CloudUploadFiles              interface{}   `json:"CloudUploadFiles"`
		CloudDownloadFiles            interface{}   `json:"CloudDownloadFiles"`
		CloudDeleteItems              interface{}   `json:"CloudDeleteItems"`
		CloudCreateFolder             interface{}   `json:"CloudCreateFolder"`
		CloudListItems                interface{}   `json:"CloudListItems"`
		CloudSyncFiles                interface{}   `json:"CloudSyncFiles"`
		CloudListFolders              interface{}   `json:"CloudListFolders"`
		CloudCopyMoveItems            interface{}   `json:"CloudCopyMoveItems"`
		EncryptFilesSymmetric         interface{}   `json:"EncryptFilesSymmetric"`
		DecryptFilesSymmetric         interface{}   `json:"DecryptFilesSymmetric"`
		EncryptFilesAsymmetric        interface{}   `json:"EncryptFilesAsymmetric"`
		DecryptFilesAsymmetric        interface{}   `json:"DecryptFilesAsymmetric"`
		WindowsUpdate                 interface{}   `json:"WindowsUpdate"`
		SystemRestoreCreate           interface{}   `json:"SystemRestoreCreate"`
		SystemRestoreDelete           interface{}   `json:"SystemRestoreDelete"`
		SystemRestoreList             interface{}   `json:"SystemRestoreList"`
		SystemRestoreRestore          interface{}   `json:"SystemRestoreRestore"`
		UnmanagedDLLExecute           interface{}   `json:"UnmanagedDLLExecute"`
		Popup                         interface{}   `json:"Popup"`
		SharepointGetLists            interface{}   `json:"SharepointGetLists"`
		SharepointCreateList          interface{}   `json:"SharepointCreateList"`
		SharepointDeleteList          interface{}   `json:"SharepointDeleteList"`
		SharepointUpdateList          interface{}   `json:"SharepointUpdateList"`
		SharepointDescribeList        interface{}   `json:"SharepointDescribeList"`
		SharepointAddListItem         interface{}   `json:"SharepointAddListItem"`
		SharepointDeleteListItem      interface{}   `json:"SharepointDeleteListItem"`
		SharepointUpdateListItem      interface{}   `json:"SharepointUpdateListItem"`
		SharepointGetListItems        interface{}   `json:"SharepointGetListItems"`
		SharepointUploadFiles         interface{}   `json:"SharepointUploadFiles"`
		SharepointDownloadFiles       interface{}   `json:"SharepointDownloadFiles"`
		SharepointListFiles           interface{}   `json:"SharepointListFiles"`
		SharepointDeleteFiles         interface{}   `json:"SharepointDeleteFiles"`
		JobReport                     interface{}   `json:"JobReport"`
		XendApp                       interface{}   `json:"XendApp"`
		CrystalReports                interface{}   `json:"CrystalReports"`
		VirtualServerList             interface{}   `json:"VirtualServerList"`
		VirtualServerStart            interface{}   `json:"VirtualServerStart"`
		VirtualServerTurnOff          interface{}   `json:"VirtualServerTurnOff"`
		VirtualServerSaveState        interface{}   `json:"VirtualServerSaveState"`
		VirtualServerReset            interface{}   `json:"VirtualServerReset"`
		VirtualServerPause            interface{}   `json:"VirtualServerPause"`
		VirtualServerCheck            interface{}   `json:"VirtualServerCheck"`
		HyperVList                    interface{}   `json:"HyperVList"`
		HyperVStart                   interface{}   `json:"HyperVStart"`
		HyperVStop                    interface{}   `json:"HyperVStop"`
		HyperVPause                   interface{}   `json:"HyperVPause"`
		HyperVSuspend                 interface{}   `json:"HyperVSuspend"`
		HyperVResume                  interface{}   `json:"HyperVResume"`
		HyperVCheck                   interface{}   `json:"HyperVCheck"`
		HyperVReset                   interface{}   `json:"HyperVReset"`
		HyperVCreateSnapshot          interface{}   `json:"HyperVCreateSnapshot"`
		HyperVApplySnapshot           interface{}   `json:"HyperVApplySnapshot"`
		HyperVDeleteSnapshot          interface{}   `json:"HyperVDeleteSnapshot"`
		SysLog                        interface{}   `json:"SysLog"`
		VMWareStartVM                 interface{}   `json:"VMWareStartVM"`
		VMWareStopVM                  interface{}   `json:"VMWareStopVM"`
		VMWareSuspendVM               interface{}   `json:"VMWareSuspendVM"`
		VMWarePauseVM                 interface{}   `json:"VMWarePauseVM"`
		VMWareResumeVM                interface{}   `json:"VMWareResumeVM"`
		VMWareResetVM                 interface{}   `json:"VMWareResetVM"`
		VMWareCheckVMStatus           interface{}   `json:"VMWareCheckVMStatus"`
		VMWareCreateVMSnapshot        interface{}   `json:"VMWareCreateVMSnapshot"`
		VMWareRevertToVMSnapshot      interface{}   `json:"VMWareRevertToVMSnapshot"`
		VMWareDeleteVMSnapshot        interface{}   `json:"VMWareDeleteVMSnapshot"`
		VMWareListVMSnapshots         interface{}   `json:"VMWareListVMSnapshots"`
		VMWareDeleteVM                interface{}   `json:"VMWareDeleteVM"`
		VMWareCloneVM                 interface{}   `json:"VMWareCloneVM"`
		VMWareInstallToolsVM          interface{}   `json:"VMWareInstallToolsVM"`
		VMWareRegisterVM              interface{}   `json:"VMWareRegisterVM"`
		VMWareUnRegisterVM            interface{}   `json:"VMWareUnRegisterVM"`
		VMWareListVM                  interface{}   `json:"VMWareListVM"`
		VMWareGuestCaptureScreen      interface{}   `json:"VMWareGuestCaptureScreen"`
		VMWareGuestCopyFile           interface{}   `json:"VMWareGuestCopyFile"`
		VMWareGuestRenameFile         interface{}   `json:"VMWareGuestRenameFile"`
		VMWareGuestDeleteFile         interface{}   `json:"VMWareGuestDeleteFile"`
		VMWareGuestDirectoryExists    interface{}   `json:"VMWareGuestDirectoryExists"`
		VMWareGuestFileExists         interface{}   `json:"VMWareGuestFileExists"`
		VMWareGuestDeleteDirectory    interface{}   `json:"VMWareGuestDeleteDirectory"`
		VMWareGuestCreateDirectory    interface{}   `json:"VMWareGuestCreateDirectory"`
		VMWareGuestCreateTempFile     interface{}   `json:"VMWareGuestCreateTempFile"`
		VMWareGuestRunCommand         interface{}   `json:"VMWareGuestRunCommand"`
		VMWareGuestOpenURL            interface{}   `json:"VMWareGuestOpenURL"`
		VMWareGuestKillProcess        interface{}   `json:"VMWareGuestKillProcess"`
		VMWareGuestListProcesses      interface{}   `json:"VMWareGuestListProcesses"`
		DynamicsCRMCreateEntity       interface{}   `json:"DynamicsCRMCreateEntity"`
		DynamicsCRMDeleteEntity       interface{}   `json:"DynamicsCRMDeleteEntity"`
		DynamicsCRMDownloadAttachment interface{}   `json:"DynamicsCRMDownloadAttachment"`
		DynamicsCRMGetAuditData       interface{}   `json:"DynamicsCRMGetAuditData"`
		DynamicsCRMGetEntity          interface{}   `json:"DynamicsCRMGetEntity"`
		DynamicsCRMListEntity         interface{}   `json:"DynamicsCRMListEntity"`
		DynamicsCRMSetAuditStatus     interface{}   `json:"DynamicsCRMSetAuditStatus"`
		DynamicsCRMStartWorkflow      interface{}   `json:"DynamicsCRMStartWorkflow"`
		DynamicsCRMUpdateEntity       interface{}   `json:"DynamicsCRMUpdateEntity"`
		DynamicsCRMUploadAttachment   interface{}   `json:"DynamicsCRMUploadAttachment"`
		DynamicsCRMDeleteAttachments  interface{}   `json:"DynamicsCRMDeleteAttachments"`
		GetChecksum                   interface{}   `json:"GetChecksum"`
		SetAttributes                 interface{}   `json:"SetAttributes"`
		ChangeOwner                   interface{}   `json:"ChangeOwner"`
		FileSetPermissions            interface{}   `json:"FileSetPermissions"`
		FolderSetPermissions          interface{}   `json:"FolderSetPermissions"`
		FolderList                    interface{}   `json:"FolderList"`
		Base64Encode                  interface{}   `json:"Base64Encode"`
		Base64Decode                  interface{}   `json:"Base64Decode"`
		ProcessorsAffinity            []interface{} `json:"ProcessorsAffinity"`
		EC2StartInstance              interface{}   `json:"EC2StartInstance"`
		EC2LaunchInstance             interface{}   `json:"EC2LaunchInstance"`
		EC2StopInstance               interface{}   `json:"EC2StopInstance"`
		EC2TerminateInstance          interface{}   `json:"EC2TerminateInstance"`
		EC2RebootInstance             interface{}   `json:"EC2RebootInstance"`
		EC2ListInstances              interface{}   `json:"EC2ListInstances"`
		EC2ListSecurityGroup          interface{}   `json:"EC2ListSecurityGroup"`
		EC2CreateSecurityGroup        interface{}   `json:"EC2CreateSecurityGroup"`
		EC2DeleteSecurityGroup        interface{}   `json:"EC2DeleteSecurityGroup"`
		EC2AuthorizeSecurityGroup     interface{}   `json:"EC2AuthorizeSecurityGroup"`
		EC2RevokeSecurityGroup        interface{}   `json:"EC2RevokeSecurityGroup"`
		EC2ListAddress                interface{}   `json:"EC2ListAddress"`
		EC2AllocateAddress            interface{}   `json:"EC2AllocateAddress"`
		EC2ReleaseAddress             interface{}   `json:"EC2ReleaseAddress"`
		EC2AssociateAddress           interface{}   `json:"EC2AssociateAddress"`
		EC2DisassociateAddress        interface{}   `json:"EC2DisassociateAddress"`
		EC2ListVolumes                interface{}   `json:"EC2ListVolumes"`
		EC2DetachVolume               interface{}   `json:"EC2DetachVolume"`
		EC2DeleteVolume               interface{}   `json:"EC2DeleteVolume"`
		EC2AttachVolume               interface{}   `json:"EC2AttachVolume"`
		EC2CreateVolume               interface{}   `json:"EC2CreateVolume"`
		EC2ListSnapshots              interface{}   `json:"EC2ListSnapshots"`
		EC2DeleteSnapshots            interface{}   `json:"EC2DeleteSnapshots"`
		EC2CreateSnapshots            interface{}   `json:"EC2CreateSnapshots"`
		EC2ListKeyPair                interface{}   `json:"EC2ListKeyPair"`
		EC2DeleteKeyPair              interface{}   `json:"EC2DeleteKeyPair"`
		EC2CreateKeyPair              interface{}   `json:"EC2CreateKeyPair"`
		PDFAddHeaderFooter            interface{}   `json:"PDFAddHeaderFooter"`
		PDFConcatenate                interface{}   `json:"PDFConcatenate"`
		PDFConvert                    interface{}   `json:"PDFConvert"`
		PDFSplit                      interface{}   `json:"PDFSplit"`
		PDFSign                       interface{}   `json:"PDFSign"`
		PDFEncrypt                    interface{}   `json:"PDFEncrypt"`
		PDFDecrypt                    interface{}   `json:"PDFDecrypt"`
		PDFClearSign                  interface{}   `json:"PDFClearSign"`
		PDFSetFields                  interface{}   `json:"PDFSetFields"`
		PDFGetFields                  interface{}   `json:"PDFGetFields"`
		PDFRemovePages                interface{}   `json:"PDFRemovePages"`
		PDFGetInformation             interface{}   `json:"PDFGetInformation"`
		PDFExtract                    interface{}   `json:"PDFExtract"`
		PDFAddAttachments             interface{}   `json:"PDFAddAttachments"`
		PDFGetAttachments             interface{}   `json:"PDFGetAttachments"`
		PDFDeleteAttachments          interface{}   `json:"PDFDeleteAttachments"`
		PDFSearch                     interface{}   `json:"PDFSearch"`
		PDFReplace                    interface{}   `json:"PDFReplace"`
		PDFInsertPages                interface{}   `json:"PDFInsertPages"`
		MSMQSendMessage               interface{}   `json:"MSMQSendMessage"`
		MSMQDeleteMessages            interface{}   `json:"MSMQDeleteMessages"`
		JobVariableSet                interface{}   `json:"JobVariableSet"`
		AzureStartVM                  interface{}   `json:"AzureStartVM"`
		AzureStopVM                   interface{}   `json:"AzureStopVM"`
		AzureRestartVM                interface{}   `json:"AzureRestartVM"`
		AzureUpdateVM                 interface{}   `json:"AzureUpdateVM"`
		AzureCreateVM                 interface{}   `json:"AzureCreateVM"`
		AzureStartWeb                 interface{}   `json:"AzureStartWeb"`
		AzureStopWeb                  interface{}   `json:"AzureStopWeb"`
		AzureRestartWeb               interface{}   `json:"AzureRestartWeb"`
		AzureRemoveWeb                interface{}   `json:"AzureRemoveWeb"`
		AzureCreateWeb                interface{}   `json:"AzureCreateWeb"`
		Office365GetCalendars         interface{}   `json:"Office365GetCalendars"`
		Office365AddCalendarEvent     interface{}   `json:"Office365AddCalendarEvent"`
		Office365UpdateCalendarEvent  interface{}   `json:"Office365UpdateCalendarEvent"`
		Office365DeleteCalendarEvent  interface{}   `json:"Office365DeleteCalendarEvent"`
		MSTeamsAddChannelMessage      interface{}   `json:"MSTeamsAddChannelMessage"`
		AmazonSNSPublishMessage       interface{}   `json:"AmazonSNSPublishMessage"`
		AmazonDynamoDBListTables      interface{}   `json:"AmazonDynamoDBListTables"`
		AmazonDynamoDBCreateTable     interface{}   `json:"AmazonDynamoDBCreateTable"`
		AmazonDynamoDBUpdateTable     interface{}   `json:"AmazonDynamoDBUpdateTable"`
		AmazonDynamoDBDeleteTable     interface{}   `json:"AmazonDynamoDBDeleteTable"`
		AmazonDynamoDBDescribeTable   interface{}   `json:"AmazonDynamoDBDescribeTable"`
		AmazonDynamoDBQueryItem       interface{}   `json:"AmazonDynamoDBQueryItem"`
		AmazonDynamoDBPutItem         interface{}   `json:"AmazonDynamoDBPutItem"`
		AmazonDynamoDBGetItem         interface{}   `json:"AmazonDynamoDBGetItem"`
		AmazonDynamoDBDeleteItem      interface{}   `json:"AmazonDynamoDBDeleteItem"`
		PushbulletSendMessage         interface{}   `json:"PushbulletSendMessage"`
		PushbulletSendLink            interface{}   `json:"PushbulletSendLink"`
		PushbulletSendFile            interface{}   `json:"PushbulletSendFile"`
		PushbulletUploadFile          interface{}   `json:"PushbulletUploadFile"`
		PushbulletSendSMS             interface{}   `json:"PushbulletSendSMS"`
		Saprfc                        interface{}   `json:"SAPRFC"`
		ImageOverlay                  interface{}   `json:"ImageOverlay"`
		ImageAdjust                   interface{}   `json:"ImageAdjust"`
		ImageCaptureScreen            interface{}   `json:"ImageCaptureScreen"`
		ImageConvert                  interface{}   `json:"ImageConvert"`
		ImageCrop                     interface{}   `json:"ImageCrop"`
		ImageFilter                   interface{}   `json:"ImageFilter"`
		ImageFlip                     interface{}   `json:"ImageFlip"`
		ImageJoin                     interface{}   `json:"ImageJoin"`
		ImageResize                   interface{}   `json:"ImageResize"`
		ImageRotate                   interface{}   `json:"ImageRotate"`
		ImageGetEXIFData              interface{}   `json:"ImageGetEXIFData"`
		ImageProfileChange            interface{}   `json:"ImageProfileChange"`
		ScanDocument                  interface{}   `json:"ScanDocument"`
		TelegramBotSend               interface{}   `json:"TelegramBotSend"`
		TelegramUserSend              interface{}   `json:"TelegramUserSend"`
		TwitterTweet                  interface{}   `json:"TwitterTweet"`
		TwitterTweetReply             interface{}   `json:"TwitterTweetReply"`
		TwitterGetStatus              interface{}   `json:"TwitterGetStatus"`
		TwitterDeleteStatus           interface{}   `json:"TwitterDeleteStatus"`
		TwitterFollowUser             interface{}   `json:"TwitterFollowUser"`
		TwitterSendMessage            interface{}   `json:"TwitterSendMessage"`
		TwitterRetweet                interface{}   `json:"TwitterRetweet"`
		TwitterLikeTweet              interface{}   `json:"TwitterLikeTweet"`
		TwitterSearchTweets           interface{}   `json:"TwitterSearchTweets"`
		TwitterGetMessages            interface{}   `json:"TwitterGetMessages"`
		TwitterGetTimeline            interface{}   `json:"TwitterGetTimeline"`
		TwitterGetMentions            interface{}   `json:"TwitterGetMentions"`
		TwitterGetFriends             interface{}   `json:"TwitterGetFriends"`
		TwitterGetFollowers           interface{}   `json:"TwitterGetFollowers"`
		JSONFilter                    interface{}   `json:"JSONFilter"`
		EnvVariableGet                interface{}   `json:"EnvVariableGet"`
		EnvVariableSet                interface{}   `json:"EnvVariableSet"`
		EnvVariableAppend             interface{}   `json:"EnvVariableAppend"`
		EnvVariableList               interface{}   `json:"EnvVariableList"`
		EnvVariableDelete             interface{}   `json:"EnvVariableDelete"`
		EMailGetHeaders               interface{}   `json:"EMailGetHeaders"`
		EMailGetMessages              interface{}   `json:"EMailGetMessages"`
		EMailGetSingleMessage         interface{}   `json:"EMailGetSingleMessage"`
		EMailDeleteSingleMessage      interface{}   `json:"EMailDeleteSingleMessage"`
		EMailDeleteMessages           interface{}   `json:"EMailDeleteMessages"`
		EMailMoveMessages             interface{}   `json:"EMailMoveMessages"`
		AMQPSendMessage               interface{}   `json:"AMQPSendMessage"`
		SlackSendMessage              interface{}   `json:"SlackSendMessage"`
		FacebookPublish               interface{}   `json:"FacebookPublish"`
		IISIsAppPoolExists            interface{}   `json:"IISIsAppPoolExists"`
		IISAddApplicationPool         interface{}   `json:"IISAddApplicationPool"`
		IISDeleteApplicationPool      interface{}   `json:"IISDeleteApplicationPool"`
		IISChangeApplicationPoolState interface{}   `json:"IISChangeApplicationPoolState"`
		IISAddWebSite                 interface{}   `json:"IISAddWebSite"`
		IISDeleteWebSite              interface{}   `json:"IISDeleteWebSite"`
		IISAddWebSiteApplication      interface{}   `json:"IISAddWebSiteApplication"`
		IISDeleteWebSiteApplication   interface{}   `json:"IISDeleteWebSiteApplication"`
		IISAddAppVirtualDirectory     interface{}   `json:"IISAddAppVirtualDirectory"`
		IISDeleteAppVirtualDirectory  interface{}   `json:"IISDeleteAppVirtualDirectory"`
		IISChangeWebSiteState         interface{}   `json:"IISChangeWebSiteState"`
		PSProcessSchedule             interface{}   `json:"PSProcessSchedule"`
		TaskInformaticaRunJob         interface{}   `json:"TaskInformaticaRunJob"`
		PSFindProcesses               interface{}   `json:"PSFindProcesses"`
		PSProcessRequest              interface{}   `json:"PSProcessRequest"`
		PSProcessReport               interface{}   `json:"PSProcessReport"`
		PSProcessUpdate               interface{}   `json:"PSProcessUpdate"`
		PSSchedulePSQuery             interface{}   `json:"PSSchedulePSQuery"`
		PSScheduleBIPublisher         interface{}   `json:"PSScheduleBIPublisher"`
		PSScheduleConQuery            interface{}   `json:"PSScheduleConQuery"`
		MobileApp                     interface{}   `json:"MobileApp"`
		IBMCognosRunReport            interface{}   `json:"IBMCognosRunReport"`
		IBMCognosRunJob               interface{}   `json:"IBMCognosRunJob"`
	} `json:"Tasks"`
	StartNotifications    []interface{} `json:"StartNotifications"`
	CompleteNotifications []interface{} `json:"CompleteNotifications"`
	ErrorNotifications    []interface{} `json:"ErrorNotifications"`
	TimeExceptions        []interface{} `json:"TimeExceptions"`
	Conditions            []interface{} `json:"Conditions"`
	TimeOut               struct {
		Use           bool `json:"Use"`
		Hours         int  `json:"Hours"`
		Minutes       int  `json:"Minutes"`
		Seconds       int  `json:"Seconds"`
		ConsiderError bool `json:"ConsiderError"`
	} `json:"TimeOut"`
	Stats struct {
		JobID               string    `json:"JobId"`
		Active              bool      `json:"Active"`
		ExitCode            int       `json:"ExitCode"`
		ExitCodeResult      int       `json:"ExitCodeResult"`
		DateLastExecution   time.Time `json:"DateLastExecution"`
		DateNextExecution   time.Time `json:"DateNextExecution"`
		DateLastExited      time.Time `json:"DateLastExited"`
		DateCreated         time.Time `json:"DateCreated"`
		DateModified        time.Time `json:"DateModified"`
		NoExecutes          int       `json:"NoExecutes"`
		ExecutionTime       float64   `json:"ExecutionTime"`
		LastTriggerID       string    `json:"LastTriggerId"`
		Status              int       `json:"Status"`
		CPUTime             float64   `json:"CPUTime"`
		TriggerCPUTime      float64   `json:"TriggerCPUTime"`
		TasksCPUTime        float64   `json:"TasksCPUTime"`
		NotificationCPUTime float64   `json:"NotificationCPUTime"`
	} `json:"Stats"`
	ID           string `json:"Id"`
	Test         bool   `json:"Test"`
	ResultOutput struct {
		Triggers interface{} `json:"Triggers"`
		TCPUTime float64     `json:"TCPUTime"`
		PCPUTime float64     `json:"PCPUTime"`
	} `json:"ResultOutput"`
	IsTaskRepository     bool          `json:"IsTaskRepository"`
	UseRunRandomValue    bool          `json:"UseRunRandomValue"`
	RunRandomValue       int           `json:"RunRandomValue"`
	Missed               bool          `json:"Missed"`
	MissedDate           string        `json:"MissedDate"`
	Name                 string        `json:"Name"`
	Description          string        `json:"Description"`
	Group                string        `json:"Group"`
	JobDebugging         bool          `json:"JobDebugging"`
	RunMissed            bool          `json:"RunMissed"`
	RunOnce              bool          `json:"RunOnce"`
	RemoveAfterExecution bool          `json:"RemoveAfterExecution"`
	RunTasksInOrder      bool          `json:"RunTasksInOrder"`
	NotStartIfRunning    bool          `json:"NotStartIfRunning"`
	QueueJobs            bool          `json:"QueueJobs"`
	CreatedBy            interface{}   `json:"CreatedBy"`
	ModifiedBy           interface{}   `json:"ModifiedBy"`
	UniqueRunID          int           `json:"UniqueRunId"`
	JobFolders           []interface{} `json:"JobFolders"`
}

/*
Get Visual Cron Jobs
*/
func (c *VCClient) GetJobs(ctx context.Context) (*Jobs, error) {
	// Get API Token before actual request to api
	token, err := GetToken(c)
	// If token was retrieved successfully continue with api request else log fatal
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	// Set token
	c.Token = token
	// Get API Endpoint for all Jobs
	log.Printf("Requesting url: %s", fmt.Sprintf("%s/Job/List?token=%s", c.BaseURL, c.Token))
	req, err := http.NewRequest("GET", fmt.Sprintf("%s/Job/List?token=%s", c.BaseURL, c.Token), nil)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)

	var res Jobs
	if err := c.sendRequest(req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
